version: '3'

services:

  mysql:
    container_name: health-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: health-db
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      health-net:
        ipv4_address: 10.5.0.2

  mq:
    container_name: health-rabbitmq
    image: rabbitmq:3.5.6-management
    expose:
        - "5672"
        - "15672"
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      health-net:
        ipv4_address: 10.5.0.3

  health-service-backend:
    container_name: health-service-backend
    depends_on:
      - mysql
      - mq
    build:
      context: ./health-service/
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: mysql
      RABBIT_URL: mq
      PORT: 8080
    networks:
      health-net:
        ipv4_address: 10.5.0.4
  
  health-consumer-backend:
    container_name: health-consumer-backend
    depends_on:
      - mq
    build:
      context: ./health-consumer/
    ports:
      - "9090:9090"
    environment:
      RABBIT_URL: mq
      PORT: 9090
    networks:
      health-net:
        ipv4_address: 10.5.0.5

networks:
  health-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16