spring:
  application:
    name: health-consumer
  rabbitmq:
    host: 'localhost'
    port: 5672
    virtual-host: '/'
    username: 'admin'
    password: 'admin'
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: ${PORT:9090}

rabbitmq:
  exchange:
    name: 'health.registry.exchange'
    type: 'topic'
    routing-key: '#'
  registry:
    enabled: true
    queue:
      name: 'health.registry.queue'