version: '3'

services:

  mysql:
    container_name: health-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: health-db
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      assembly-net:
        ipv4_address: 10.5.0.2

  health-service-backend:
    container_name: health-service-backend
    depends_on:
      - mysql
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      assembly-net:
        ipv4_address: 10.5.0.3

networks:
  assembly-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16