spring:
  application:
    name: health-service
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:3306/health-db?allowPublicKeyRetrieval=true&autoReconnect=true&autoReconnectForPools=true&socketTimeout=5000&connectTimeout=1000&useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 10
    initialSize: 1
    minIdle: 1
    maxIdle: 1
    testWhileIdle: true
    validationQuery: SELECT 1
    socketTimeout: 3000
    validationTimeout: 500
    connectionTimeout: 1000
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  hibernate:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

security:
  oauth2:
    resource:
      id: bcrypt