name: Java Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend/health-service

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Gradle
        run: ./gradlew clean test
        working-directory: ${{env.working-directory}}
      - run: echo "🍏 This job's status is ${{ job.status }}."